In [1]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\github\data-science\.venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in d:\github\data-science\.venv\lib\site-packages (from scikit-learn) (2.3.3)
Requirement already satisfied: scipy>=1.10.0 in d:\github\data-science\.venv\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in d:\github\data-science\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\github\data-science\.venv\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing  import MinMaxScaler

In [4]:
df = pd.read_csv('D:\GitHub\Data-Science\datasets\Churn_Modelling.csv')

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Professor\AppData\Local\Temp\ipykernel_19792\4005726195.py:1: SyntaxWarning: invalid escape sequence '\G'
  df = pd.read_csv('D:\GitHub\Data-Science\datasets\Churn_Modelling.csv')

In [5]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0

In [6]:
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1

In [7]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,42.0,41.0,42.0,39.0,NaN,44.0,NaN,29.0,44.0,27.0,...,33.0,53.0,36.0,28.0,29.0,39.0,35.0,36.0,42.0,28.0
Tenure,2.0,1.0,8.0,1.0,NaN,8.0,NaN,4.0,NaN,2.0,...,3.0,4.0,2.0,7.0,2.0,5.0,10.0,7.0,3.0,4.0
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [8]:
new_df = pd.DataFrame(df,columns= ['Age','Tenure'])

In [10]:
new_df.isnull().sum()

Age       2
Tenure    3
dtype: int64

In [11]:
new_df['Age'] = new_df['Age'].fillna(new_df['Age'].mean())

In [12]:
new_df.isnull().sum()

Age       0
Tenure    3
dtype: int64

In [17]:
scaler = MinMaxScaler()
normalized = scaler.fit_transform(new_df)

In [18]:
print(normalized)

[[0.32432432 0.2       ]
 [0.31081081 0.1       ]
 [0.32432432 0.8       ]
 ...
 [0.24324324 0.7       ]
 [0.32432432 0.3       ]
 [0.13513514 0.4       ]]