In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [29]:
path = 'D:\GitHub\Data-Science\datasets\Churn_Modelling.csv'

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Professor\AppData\Local\Temp\ipykernel_17664\4043283465.py:1: SyntaxWarning: invalid escape sequence '\G'
  path = 'D:\GitHub\Data-Science\datasets\Churn_Modelling.csv'

In [30]:
df = pd.read_csv(path)

In [31]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0

In [32]:
df.drop(columns=['CustomerId','RowNumber','Surname'], axis=1,inplace=True)

In [33]:
df.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0
4,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0

In [34]:
df['Gender'].isnull().sum()

np.int64(0)

In [35]:
df['Gender'] = df['Gender'].fillna('Male')

In [36]:
le = preprocessing.LabelEncoder()

df['Gender_Label'] = le.fit_transform(df.Gender.values)

In [37]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label
0,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1,0
1,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0,0

### One Hot Encoding

In [38]:
one_hot = pd.get_dummies(df['Geography'])

In [39]:
one_hot

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [40]:
one_hot_df = pd.get_dummies(df)

In [42]:
one_hot_df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42.0,2.0,0.00,1,1,1,101348.88,1,0,True,False,False,True,False
1,608,41.0,1.0,83807.86,1,0,1,112542.58,0,0,False,False,True,True,False
2,502,42.0,8.0,159660.80,3,1,0,113931.57,1,0,True,False,False,True,False
3,699,39.0,1.0,0.00,2,0,0,93826.63,0,0,True,False,False,True,False
4,850,NaN,NaN,125510.82,1,1,1,79084.10,0,0,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39.0,5.0,0.00,2,1,0,96270.64,0,1,True,False,False,False,True
9996,516,35.0,10.0,57369.61,1,1,1,101699.77,0,1,True,False,False,False,True
9997,709,36.0,7.0,0.00,1,0,1,42085.58,1,0,True,False,False,True,False
9998,772,42.0,3.0,75075.31,2,1,0,92888.52,1,1,False,True,False,False,True
9999,792,28.0,4.0,130142.79,1,1,0,38190.78,0,0,True,False,False,True,False

### Dummy Encoding

In [43]:
df_dummies = pd.get_dummies(df,drop_first=True)

In [44]:
df_dummies

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_Germany,Geography_Spain,Gender_Male
0,619,42.0,2.0,0.00,1,1,1,101348.88,1,0,False,False,False
1,608,41.0,1.0,83807.86,1,0,1,112542.58,0,0,False,True,False
2,502,42.0,8.0,159660.80,3,1,0,113931.57,1,0,False,False,False
3,699,39.0,1.0,0.00,2,0,0,93826.63,0,0,False,False,False
4,850,NaN,NaN,125510.82,1,1,1,79084.10,0,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39.0,5.0,0.00,2,1,0,96270.64,0,1,False,False,True
9996,516,35.0,10.0,57369.61,1,1,1,101699.77,0,1,False,False,True
9997,709,36.0,7.0,0.00,1,0,1,42085.58,1,0,False,False,False
9998,772,42.0,3.0,75075.31,2,1,0,92888.52,1,1,True,False,True
9999,792,28.0,4.0,130142.79,1,1,0,38190.78,0,0,False,False,False

In [46]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in d:\github\data-science\.venv\lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: pandas>=1.0.5 in d:\github\data-science\.venv\lib\site-packages (from category_encoders) (2.3.3)
Collecting patsy>=0.5.1 (from category_encoders)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in d:\github\data-science\.venv\lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in d:\github\data-science\.venv\lib\site-packages (from category_encoders) (1.16.3)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.6-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\github\data-science\.venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\github\data-science\.venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\github\data-science\.venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: joblib>=1.3.0 in d:\github\data-science\.venv\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\github\data-science\.venv\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in d:\github\data-science\.venv\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)
Requirement already satisfied: six>=1.5 in d:\github\data-science\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/85.9 kB ? eta -:--:--
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   -------------- ------------------------- 30.7/85.9 kB 43.7 kB/s eta 0:00:02
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ------------------- -------------------- 41.0/85.9 kB 11.6 kB/s eta 0:00:04
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   ---------------------------- ----------- 61.4/85.9 kB 14.6 kB/s eta 0:00:02
   -------------------------------------- - 81.9/85.9 kB 18.3 kB/s eta 0:00:01
   -------------------------------------- - 81.9/85.9 kB 18.3 kB/s eta 0:00:01
   -------------------------------------- - 81.9/85.9 kB 18.3 kB/s eta 0:00:01
   -------------------------------------- - 81.9/85.9 kB 18.3 kB/s eta 0:00:01
   -------------------------------------- - 81.9/85.9 kB 18.3 kB/s eta 0:00:01
   ---------------------------------------- 85.9/85.9 kB 18.3 kB/s eta 0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
   ---------------------------------------- 0.0/233.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/233.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/233.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/233.3 kB ? eta -:--:--
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ----- ---------------------------------- 30.7/233.3 kB 59.7 kB/s eta 0:00:04
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ------- -------------------------------- 41.0/233.3 kB 37.1 kB/s eta 0:00:06
   ---------- ----------------------------- 61.4/233.3 kB 26.2 kB/s eta 0:00:07
   ------------ --------------------------- 71.7/233.3 kB 30.5 kB/s eta 0:00:06
   ------------ --------------------------- 71.7/233.3 kB 30.5 kB/s eta 0:00:06
   ------------ --------------------------- 71.7/233.3 kB 30.5 kB/s eta 0:00:06
   ------------ --------------------------- 71.7/233.3 kB 30.5 kB/s eta 0:00:06
   ------------ --------------------------- 71.7/233.3 kB 30.5 kB/s eta 0:00:06
   ------------ --------------------------- 71.7/233.3 kB 30.5 kB/s eta 0:00:06
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   --------------- ------------------------ 92.2/233.3 kB 36.2 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   ------------------ -------------------- 112.6/233.3 kB 34.3 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   -------------------- ------------------ 122.9/233.3 kB 33.1 kB/s eta 0:00:04
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ----------------------- --------------- 143.4/233.3 kB 34.4 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ------------------------- ------------- 153.6/233.3 kB 32.1 kB/s eta 0:00:03
   ----------------------------- --------- 174.1/233.3 kB 31.4 kB/s eta 0:00:02
   ----------------------------- --------- 174.1/233.3 kB 31.4 kB/s eta 0:00:02
   ----------------------------- --------- 174.1/233.3 kB 31.4 kB/s eta 0:00:02
   ----------------------------- --------- 174.1/233.3 kB 31.4 kB/s eta 0:00:02
   ----------------------------- --------- 174.1/233.3 kB 31.4 kB/s eta 0:00:02
   ----------------------------- --------- 174.1/233.3 kB 31.4 kB/s eta 0:00:02

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [47]:
from category_encoders import TargetEncoder