In [2]:
!pip  install matplotlib

Collecting matplotlib
  Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.0-cp312-cp312-win_amd64.whl.metadata (119 kB)
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     ------ ------------------------------ 20.5/119.6 kB 162.5 kB/s eta 0:00:01
     ------ ------------------------------ 20.5/119.6 kB 162.5 kB/s eta 0:00:01
     ------ ------------------------------ 20.5/119.6 kB 162.5 kB/s eta 0:00:01
     ------ ------------------------------ 20.5/119.6 kB 162.5 kB/s eta 0:00:01
     ------ ------------------------------ 20.5/119.6 kB 162.5 kB/s eta 0:00:01
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     --------- ---------------------------- 30.7/119.6 kB 72.9 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------- ------------------------ 41.0/119.6 kB 39.3 kB/s eta 0:00:02
     ------------------- ------------------ 61.4/119.6 kB 45.5 kB/s eta 0:00:02
     ------------------- ------------------ 61.4/119.6 kB 45.5 kB/s eta 0:00:02
     ------------------- ------------------ 61.4/119.6 kB 45.5 kB/s eta 0:00:02
     ------------------- ------------------ 61.4/119.6 kB 45.5 kB/s eta 0:00:02
     ---------------------- --------------- 71.7/119.6 kB 47.4 kB/s eta 0:00:02
     ---------------------- --------------- 71.7/119.6 kB 47.4 kB/s eta 0:00:02
     ---------------------- --------------- 71.7/119.6 kB 47.4 kB/s eta 0:00:02
     ---------------------- --------------- 71.7/119.6 kB 47.4 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 54.0 kB/s eta 0:00:01
     ----------------------------- -------- 92.2/119.6 kB 54.0 kB/s eta 0:00:01
     ----------------------------- -------- 92.2/119.6 kB 54.0 kB/s eta 0:00:01
     ----------------------------- -------- 92.2/119.6 kB 54.0 kB/s eta 0:00:01
     ---------------------------------- -- 112.6/119.6 kB 60.7 kB/s eta 0:00:01
     ------------------------------------- 119.6/119.6 kB 62.5 kB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in d:\github\data-science\.env\lib\site-packages (from matplotlib) (2.4.0)
Requirement already satisfied: packaging>=20.0 in d:\github\data-science\.env\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.1.1-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in d:\github\data-science\.env\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in d:\github\data-science\.env\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.0-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
    --------------------------------------- 0.0/2.3 MB 186.2 kB/s eta 0:00:13
    --------------------------------------- 0.0/2.3 MB 186.2 kB/s eta 0:00:13
    --------------------------------------- 0.0/2.3 MB 140.3 kB/s eta 0:00:17
    --------------------------------------- 0.0/2.3 MB 140.3 kB/s eta 0:00:17
    --------------------------------------- 0.0/2.3 MB 140.3 kB/s eta 0:00:17
   - -------------------------------------- 0.1/2.3 MB 156.1 kB/s eta 0:00:15
   - -------------------------------------- 0.1/2.3 MB 151.3 kB/s eta 0:00:15
   - -------------------------------------- 0.1/2.3 MB 151.3 kB/s eta 0:00:15
   - -------------------------------------- 0.1/2.3 MB 151.3 kB/s eta 0:00:15
   - -------------------------------------- 0.1/2.3 MB 151.3 kB/s eta 0:00:15
   - -------------------------------------- 0.1/2.3 MB 141.7 kB/s eta 0:00:16
   - -------------------------------------- 0.1/2.3 MB 141.7 kB/s eta 0:00:16
   - -------------------------------------- 0.1/2.3 MB 145.7 kB/s eta 0:00:16
   - -------------------------------------- 0.1/2.3 MB 145.7 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.3 MB 147.0 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.3 MB 147.0 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.3 MB 149.4 kB/s eta 0:00:15
   -- ------------------------------------- 0.1/2.3 MB 149.4 kB/s eta 0:00:15
   -- ------------------------------------- 0.1/2.3 MB 149.4 kB/s eta 0:00:15
   -- ------------------------------------- 0.2/2.3 MB 141.1 kB/s eta 0:00:16
   -- ------------------------------------- 0.2/2.3 MB 141.1 kB/s eta 0:00:16
   -- ------------------------------------- 0.2/2.3 MB 141.1 kB/s eta 0:00:16
   -- ------------------------------------- 0.2/2.3 MB 143.6 kB/s eta 0:00:16
   -- ------------------------------------- 0.2/2.3 MB 143.6 kB/s eta 0:00:16
   --- ------------------------------------ 0.2/2.3 MB 141.0 kB/s eta 0:00:16
   --- ------------------------------------ 0.2/2.3 MB 141.0 kB/s eta 0:00:16
   --- ------------------------------------ 0.2/2.3 MB 141.0 kB/s eta 0:00:16
   --- ------------------------------------ 0.2/2.3 MB 141.5 kB/s eta 0:00:16
   --- ------------------------------------ 0.2/2.3 MB 141.5 kB/s eta 0:00:16
   --- ------------------------------------ 0.2/2.3 MB 144.8 kB/s eta 0:00:15
   --- ------------------------------------ 0.2/2.3 MB 144.8 kB/s eta 0:00:15
   ---- ----------------------------------- 0.2/2.3 MB 142.8 kB/s eta 0:00:15
   ---- ----------------------------------- 0.2/2.3 MB 142.8 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 147.0 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 147.0 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 143.7 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 143.7 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 143.7 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 145.1 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 145.1 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.3 MB 145.1 kB/s eta 0:00:15
   ----- ---------------------------------- 0.3/2.3 MB 143.9 kB/s eta 0:00:15
   ----- ---------------------------------- 0.3/2.3 MB 143.9 kB/s eta 0:00:15
   ----- ---------------------------------- 0.3/2.3 MB 142.5 kB/s eta 0:00:15
   ----- ---------------------------------- 0.3/2.3 MB 142.5 kB/s eta 0:00:15
   ----- ---------------------------------- 0.3/2.3 MB 145.6 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.3 MB 145.6 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.3 MB 145.2 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.3 MB 145.2 kB/s eta 0:00:14
   ------ --------------------------------- 0.4/2.3 MB 146.1 kB/s eta 0:00:14
   ------ --------------------------------- 0.4/2.3 MB 146.1 kB/s eta 0:00:14
   ------ --------------------------------- 0.4/2.3 MB 149.7 kB/s eta 0:00:13
   ------ --------------------------------- 0.4/2.3 MB 149.7 kB/s eta 0:00:13
   ------ --------------------------------- 0.4/2.3 MB 148.2 kB/s eta 0:00:14
   ------ --------------------------------- 0.4/2.3 MB 148.2 kB/s eta 0:00:14
   ------- -------------------------------- 0.4/2.3 MB 151.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.4/2.3 MB 151.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.4/2.3 MB 151.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.4/2.3 MB 149.2 kB/s eta 0:00:13
   ------- -------------------------------- 0.4/2.3 MB 149.2 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.3 MB 150.7 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.3 MB 150.7 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 152.0 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 152.0 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 152.0 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 149.3 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 149.3 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 151.2 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 151.2 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 150.0 kB/s eta 0:00:13
   -------- ------------------------------- 0.5/2.3 MB 149.6 kB/s eta 0:00:13
   --------- ------------------------------ 0.5/2.3 MB 151.9 kB/s eta 0:00:12
   --------- ------------------------------ 0.5/2.3 MB 151.9 kB/s eta 0:00:12
   --------- ------------------------------ 0.6/2.3 MB 153.0 kB/s eta 0:00:12
   --------- ------------------------------ 0.6/2.3 MB 153.0 kB/s eta 0:00:12
   --------- ------------------------------ 0.6/2.3 MB 153.0 kB/s eta 0:00:12
   --------- ------------------------------ 0.6/2.3 MB 151.2 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.5 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.5 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.1 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.1 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.1 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 152.8 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 152.8 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.7 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.7 kB/s eta 0:00:12
   ---------- ----------------------------- 0.6/2.3 MB 153.7 kB/s eta 0:00:12
   ----------- ---------------------------- 0.6/2.3 MB 151.6 kB/s eta 0:00:12
   ----------- ---------------------------- 0.6/2.3 MB 151.6 kB/s eta 0:00:12
   ----------- ---------------------------- 0.7/2.3 MB 153.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 153.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 153.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 153.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 149.5 kB/s eta 0:00:12
   ----------- ---------------------------- 0.7/2.3 MB 149.5 kB/s eta 0:00:12
   ----------- ---------------------------- 0.7/2.3 MB 150.4 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 150.4 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 150.4 kB/s eta 0:00:11
   ----------- ---------------------------- 0.7/2.3 MB 150.4 kB/s eta 0:00:11
   ------------ --------------------------- 0.7/2.3 MB 150.2 kB/s eta 0:00:11
   ------------ --------------------------- 0.7/2.3 MB 150.2 kB/s eta 0:00:11
   ------------ --------------------------- 0.7/2.3 MB 150.2 kB/s eta 0:00:11
   ------------ --------------------------- 0.7/2.3 MB 150.2 kB/s eta 0:00:11
   ------------ --------------------------- 0.7/2.3 MB 150.2 kB/s eta 0:00:11
   ------------ --------------------------- 0.7/2.3 MB 145.2 kB/s eta 0:00:12
   ------------ --------------------------- 0.7/2.3 MB 145.2 kB/s eta 0:00:12
   ------------ --------------------------- 0.7/2.3 MB 145.2 kB/s eta 0:00:12
   ------------ --------------------------- 0.7/2.3 MB 145.2 kB/s eta 0:00:12
   ------------ --------------------------- 0.7/2.3 MB 143.9 kB/s eta 0:00:12
   ------------ --------------------------- 0.7/2.3 MB 143.9 kB/s eta 0:00:12
   ------------ --------------------------- 0.7/2.3 MB 143.9 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 141.5 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 141.5 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 141.5 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 141.5 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 140.4 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 140.4 kB/s eta 0:00:12
   ------------- -------------------------- 0.8/2.3 MB 141.7 kB/s eta 0:00:11
   ------------- -------------------------- 0.8/2.3 MB 141.2 kB/s eta 0:00:11
   ------------- -------------------------- 0.8/2.3 MB 141.2 kB/s eta 0:00:11
   ------------- -------------------------- 0.8/2.3 MB 141.2 kB/s eta 0:00:11
   ------------- -------------------------- 0.8/2.3 MB 141.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 140.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 140.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 140.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 140.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 140.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.3 MB 137.2 kB/s eta 0:00:11
   -------------- ------------------------- 0.9/2.3 MB 129.2 kB/s eta 0:00:12
   -------------- ------------------------- 0.9/2.3 MB 129.2 kB/s eta 0:00:12
   -------------- ------------------------- 0.9/2.3 MB 129.2 kB/s eta 0:00:12
   -------------- ------------------------- 0.9/2.3 MB 129.2 kB/s eta 0:00:12
   -------------- ------------------------- 0.9/2.3 MB 129.2 kB/s eta 0:00:12
   -------------- ------------------------- 0.9/2.3 MB 129.2 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.6 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.6 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.1 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.1 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.1 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.1 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.2 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.2 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 126.2 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 125.2 kB/s eta 0:00:12
   --------------- ------------------------ 0.9/2.3 MB 125.2 kB/s eta 0:00:12
   ---------------- ----------------------- 0.9/2.3 MB 125.8 kB/s eta 0:00:12
   ---------------- ----------------------- 0.9/2.3 MB 125.8 kB/s eta 0:00:12
   ---------------- ----------------------- 0.9/2.3 MB 125.8 kB/s eta 0:00:12
   ---------------- ----------------------- 0.9/2.3 MB 125.8 kB/s eta 0:00:12
   ---------------- ----------------------- 1.0/2.3 MB 125.7 kB/s eta 0:00:11
   ---------------- ----------------------- 1.0/2.3 MB 125.7 kB/s eta 0:00:11
   ---------------- ----------------------- 1.0/2.3 MB 125.7 kB/s eta 0:00:11
   ---------------- ----------------------- 1.0/2.3 MB 124.2 kB/s eta 0:00:11
   ---------------- ----------------------- 1.0/2.3 MB 124.2 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 125.6 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 125.6 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 124.9 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 124.9 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 124.9 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 125.7 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 127.0 kB/s eta 0:00:11
   ----------------- ---------------------- 1.0/2.3 MB 127.0 kB/s eta 0:00:11
   ------------------ --------------------- 1.1/2.3 MB 127.1 kB/s eta 0:00:11
   ------------------ --------------------- 1.1/2.3 MB 127.1 kB/s eta 0:00:11
   ------------------ --------------------- 1.1/2.3 MB 127.1 kB/s eta 0:00:11
   ------------------ --------------------- 1.1/2.3 MB 127.1 kB/s eta 0:00:11
   ------------------ --------------------- 1.1/2.3 MB 126.4 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 126.4 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 126.4 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 125.8 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 125.8 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 125.8 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 125.7 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 125.7 kB/s eta 0:00:10
   ------------------ --------------------- 1.1/2.3 MB 125.7 kB/s eta 0:00:10
   ------------------- -------------------- 1.1/2.3 MB 126.0 kB/s eta 0:00:10
   ------------------- -------------------- 1.1/2.3 MB 126.0 kB/s eta 0:00:10
   ------------------- -------------------- 1.1/2.3 MB 126.0 kB/s eta 0:00:10
   ------------------- -------------------- 1.1/2.3 MB 125.2 kB/s eta 0:00:10
   ------------------- -------------------- 1.1/2.3 MB 125.2 kB/s eta 0:00:10

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [4]:
data = pd.read_csv('D:\GitHub\Data-Science\datasets\Churn_Modelling.csv')

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Professor\AppData\Local\Temp\ipykernel_15708\932699445.py:1: SyntaxWarning: invalid escape sequence '\G'
  data = pd.read_csv('D:\GitHub\Data-Science\datasets\Churn_Modelling.csv')

In [5]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5.0,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10.0,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7.0,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3.0,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4.0,130142.79,1,1,0,38190.78,0

In [6]:
df = data

In [7]:
df.head(1)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2.0,0.0,1,1,1,101348.88,1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              9998 non-null   float64
 7   Tenure           9997 non-null   float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(4), int64(7), object(3)
memory usage: 1.1+ MB

In [10]:
df.drop(columns= ['CustomerId', 'RowNumber','Surname'],axis=1, inplace=True)

In [11]:
df.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0
4,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0

In [12]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

## Handling missing values

In [13]:
df.Gender.mode()

0    Male
Name: Gender, dtype: object

In [15]:
df['Gender'] = df['Gender'].fillna('Male')

In [16]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

## Label  Encoding

In [19]:
le = preprocessing.LabelEncoder()
df['Gender_label' ] = le.fit_transform(df.Gender.values)

In [22]:
df.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label
0,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1,0
1,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0,0
5,645,Spain,Male,44.0,8.0,113755.78,2,1,0,149756.71,1,1
6,822,France,Male,NaN,NaN,0.00,2,1,1,10062.80,0,1
7,376,Germany,Female,29.0,4.0,115046.74,4,1,0,119346.88,1,0
8,501,France,Male,44.0,NaN,142051.07,2,0,1,74940.50,0,1
9,684,France,Male,27.0,2.0,134603.88,1,1,1,71725.73,0,1

## OneHot Endoding

In [24]:
one_hot = pd.get_dummies(df['Geography'])

In [26]:
df.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label
0,619,France,Female,42.0,2.0,0.00,1,1,1,101348.88,1,0
1,608,Spain,Female,41.0,1.0,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42.0,8.0,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39.0,1.0,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,NaN,NaN,125510.82,1,1,1,79084.10,0,0
5,645,Spain,Male,44.0,8.0,113755.78,2,1,0,149756.71,1,1
6,822,France,Male,NaN,NaN,0.00,2,1,1,10062.80,0,1
7,376,Germany,Female,29.0,4.0,115046.74,4,1,0,119346.88,1,0
8,501,France,Male,44.0,NaN,142051.07,2,0,1,74940.50,0,1
9,684,France,Male,27.0,2.0,134603.88,1,1,1,71725.73,0,1

In [30]:
df_dumies = pd.get_dummies(df)
df_dumies.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42.0,2.0,0.00,1,1,1,101348.88,1,0,True,False,False,True,False
1,608,41.0,1.0,83807.86,1,0,1,112542.58,0,0,False,False,True,True,False
2,502,42.0,8.0,159660.80,3,1,0,113931.57,1,0,True,False,False,True,False
3,699,39.0,1.0,0.00,2,0,0,93826.63,0,0,True,False,False,True,False
4,850,NaN,NaN,125510.82,1,1,1,79084.10,0,0,False,False,True,True,False

## Dummy Encoding

In [31]:
df_dummies_de = pd.get_dummies(df,drop_first =True)

In [32]:
df_dummies_de.head(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_Germany,Geography_Spain,Gender_Male
0,619,42.0,2.0,0.00,1,1,1,101348.88,1,0,False,False,False
1,608,41.0,1.0,83807.86,1,0,1,112542.58,0,0,False,True,False
2,502,42.0,8.0,159660.80,3,1,0,113931.57,1,0,False,False,False
3,699,39.0,1.0,0.00,2,0,0,93826.63,0,0,False,False,False
4,850,NaN,NaN,125510.82,1,1,1,79084.10,0,0,False,True,False
5,645,44.0,8.0,113755.78,2,1,0,149756.71,1,1,False,True,True
6,822,NaN,NaN,0.00,2,1,1,10062.80,0,1,False,False,True
7,376,29.0,4.0,115046.74,4,1,0,119346.88,1,0,True,False,False
8,501,44.0,NaN,142051.07,2,0,1,74940.50,0,1,False,False,True
9,684,27.0,2.0,134603.88,1,1,1,71725.73,0,1,False,False,True